stages:
  - push
Trigger Push to Launcher:
  variables:
      DESCRIPTION: "description.toml"
      PACKAGE: "package.toml"
      ORG_NAME: "$CI_PROJECT_NAMESPACE"
      REPO_NAME: "$CI_PROJECT_NAME"
      BRANCH: "$CI_COMMIT_BRANCH"
  stage: push
  trigger:
    project: omni-cd/toml-database
    branch: external
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
